# Generated by Django 3.2.5 on 2021-07-05 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chantingApp', '0004_alter_chanting_users_phone_no'),
    ]

    operations = [
        migrations.DeleteModel(
            name='chanting_users',
        ),
    ]
