# Generated by Django 3.2.5 on 2021-07-06 12:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chantingApp', '0010_rename_chanting_dashboard_chanting_menu'),
    ]

    operations = [
        migrations.AddField(
            model_name='chanting_menu',
            name='tot_chant_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='self_chant_dashboard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('japa_count', models.IntegerField(blank=True, null=True)),
                ('japa_mala_count', models.IntegerField(blank=True, null=True)),
                ('email_id', models.CharField(max_length=100)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent_chant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='chantingApp.chanting_menu')),
            ],
        ),
    ]
