# Generated by Django 3.2.5 on 2021-07-21 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chantingApp', '0011_auto_20210706_1233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='self_chant_dashboard',
            name='japa_count',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
