# Generated by Django 3.2.5 on 2021-07-24 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chantingApp', '0012_alter_self_chant_dashboard_japa_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chanting_users',
            name='first_name',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='chanting_users',
            name='last_name',
            field=models.CharField(max_length=40),
        ),
    ]
