# Generated by Django 3.2.5 on 2021-07-05 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chantingApp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='chanting_users',
        ),
    ]
