# Generated by Django 3.2.5 on 2021-07-05 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chantingApp', '0006_chanting_users'),
    ]

    operations = [
        migrations.DeleteModel(
            name='chanting_users',
        ),
    ]
