# Generated by Django 3.2.5 on 2021-07-05 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chantingApp', '0009_chanting_dashboard'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='chanting_dashboard',
            new_name='chanting_menu',
        ),
    ]
